name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop
      - test

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add build/test steps here

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying to production..."

      - name: Deploy to QA
        if: github.ref == 'refs/heads/develop'
        run: echo "Deploying to QA..."

      - name: Deploy to test
        if: github.ref == 'refs/heads/test'
        run: echo "Deploying to test environment..."
